version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: planeks_news
    command: gunicorn planeks_news.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:12.0-alpine
    container_name: planeks_news_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: on-failure
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
    restart: on-failure

volumes:
  postgres_data:
  static_volume:
  media_volume:
