version: '3.7'

services:
  web:
    build: ./app
    container_name: planeks_news
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - rabbitmq
      - db
    image: web_image
    networks:
      - default
    restart: on-failure
  db:
    image: postgres:12.0-alpine
    container_name: planeks_news_db
    volumes:
      - postgres_data:/var/lid/postgresql/data/
    env_file:
      - ./.env.dev.db
    restart: on-failure
    networks:
      - default
  rabbitmq:
    image: rabbitmq:latest
    container_name: planeks_news_rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    env_file:
      - ./.env.dev
    networks:
      - default
  celere_worker:
    container_name: celery_worker
    command: sh -c "celery -A planeks_news worker -l info"
    image: web_image
    env_file:
      - ./.env.dev
    networks:
      - default
    restart: on-failure
    depends_on:
      - web
      - db
      - rabbitmq

volumes:
  postgres_data:

networks:
  default:
