version: '3.7'

services:
  web:
    build: ./app
    container_name: planeks_news
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:12.0-alpine
    container_name: planeks_news_db
    volumes:
      - postgres_data:/var/lid/postgresql/data/
    env_file:
      - ./.env.dev.db
    restart: on-failure

volumes:
  postgres_data:
