# Generated by Django 3.0.5 on 2020-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('', ''), ('APPROVE', 'APPROVE'), ('DECLINE', 'DECLINE')], default='', max_length=7),
        ),
    ]
