# Generated by Django 3.0.5 on 2020-04-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('-------', '------'), ('APPROVE', 'APPROVE'), ('DECLINE', 'DECLINE')], default='-------', max_length=7),
        ),
    ]
