# Generated by Django 3.0.5 on 2020-04-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200403_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_confirmed_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
