# Generated by Django 3.0.5 on 2020-04-06 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('codename', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('codename', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('permissions', models.ManyToManyField(related_name='roles', to='users.Permission')),
            ],
            options={
                'ordering': ['codename'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='USER', on_delete=django.db.models.deletion.CASCADE, to='users.Role'),
        ),
    ]
